// PT lang variables

tinyMCE.addToLang('',{
bold_desc : 'Negrito',
italic_desc : 'ItÃ¡lico',
underline_desc : 'Sublinhar',
striketrough_desc : 'Riscado',
justifyleft_desc : 'Alinhar Ã¡ esquerda',
justifycenter_desc : 'Alinhar ao centro',
justifyright_desc : 'Alinhar Ã¡ direita',
justifyfull_desc : 'Justificado',
bullist_desc : 'Lista nÃ£o ordenada',
numlist_desc : 'Lista ordenada',
outdent_desc : 'Retirar indentaÃ§Ã£o',
indent_desc : 'Indentar',
undo_desc : 'Desfazer',
redo_desc : 'Refazer',
link_desc : 'Inserir HiperligaÃ§Ã£o',
unlink_desc : 'Remover hiperligaÃ§Ã£o',
image_desc : 'Inserir ReferÃªncia a imagem externa',
object_desc : 'Inserir Objecto MultimÃ©dia da Galeria',
cleanup_desc : 'Limpeza de cÃ³digo',
focus_alert : 'Uma instÃ¢ncia do editor deverÃ¡ estar seleccionada antes de utilizar este comando.',
edit_confirm : 'Deseja utilizar o modo visual de ediÃ§Ã£o para ezta Ã¡rea de texto?',
insert_link_title : 'Inserir/editar hiperligaÃ§Ã£o',
insert : 'Inserir',
update : 'Actualizar',
cancel : 'Cancelar',
insert_link_url : 'URL de hiperligaÃ§Ã£o',
insert_link_target : 'Destino',
insert_link_target_same : 'Abrir endereÃ§o na mesma janela',
insert_link_target_blank : 'Abrir endereÃ§o numa nova janela',
insert_image_title : 'Inserir/editar imagem',
insert_image_src : 'EndereÃ§o da imagem',
insert_image_alt : 'DescriÃ§Ã£o alt.',
help_desc : 'Ajuda',
bold_img : "bold.gif",
italic_img : "italic.gif",
underline_img : "underline.gif",
clipboard_msg : 'Copiar/Cortar/Colar nÃ£o estÃ¡ disponÃ­vel em Mozilla and Firefox.\nPretende obter mais informaÃ§Ã£o acerca desta questÃ£o?',
popup_blocked : 'Sorry, but we have noticed that your popup-blocker has disabled a window that provides application functionality. You will need to disable popup blocking on this site in order to fully utilize this tool.'
});
